apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.envConfigMapName }}
  labels:
    {{- include "enmedd-stack.labels" . | nindent 4 }}
data:
  INTERNAL_URL: "http://{{ include "enmedd-stack.fullname" . }}-api-service:{{ .Values.api.service.port | default 8080 }}"
  POSTGRES_HOST: {{ .Release.Name }}-postgresql
  VESPA_HOST: "document-index-service"
  REDIS_HOST: {{ .Release.Name }}-redis-master
  MODEL_SERVER_HOST: "{{ include "enmedd-stack.fullname" . }}-inference-model-service"
  INDEXING_MODEL_SERVER_HOST: "{{ include "enmedd-stack.fullname" . }}-indexing-model-service"
{{- range $key, $value := .Values.configMap }}
  {{ $key }}: "{{ $value }}"
{{- end }}