"""Add workspace user role

Revision ID: 17ca0f0827de
Revises: a2d61fc58c5b
Create Date: 2024-11-12 17:20:39.674425

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "17ca0f0827de"
down_revision = "a2d61fc58c5b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workspace__users",
        sa.Column(
            "role",
            sa.Enum("BASIC", "ADMIN", name="userrole", native_enum=False),
            nullable=False,
            server_default="BASIC",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspace__users", "role")
    # ### end Alembic commands ###
