"""Add teamspace_id column in InviteToken

Revision ID: 6b3dc91e4b2b
Revises: 800ea858cae8
Create Date: 2024-12-03 11:06:35.512027

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6b3dc91e4b2b"
down_revision = "800ea858cae8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invite_token", sa.Column("teamspace_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invite_token", "teamspace_id")
    # ### end Alembic commands ###
