"""is_visible teamspace_assistant

Revision ID: a5dd0473413d
Revises: bd77ade2f151
Create Date: 2025-01-04 08:34:27.275426

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a5dd0473413d"
down_revision = "bd77ade2f151"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistant__teamspace",
        sa.Column(
            "is_visible", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assistant__teamspace", "is_visible")
    # ### end Alembic commands ###
