"""additional invite_token columns

Revision ID: bd77ade2f151
Revises: 15b67fe0edc7
Create Date: 2024-12-27 14:44:51.526355

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "bd77ade2f151"
down_revision = "15b67fe0edc7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invite_token",
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "invite_token",
        sa.Column(
            "is_expired",
            sa.Boolean(),
            default=False,
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###

    # Set `expires_at` to 7 days after `created_at` and update `is_expired`
    connection = op.get_bind()
    connection.execute(
        sa.text(
            """
            UPDATE invite_token
            SET expires_at = created_at + interval '7 days',
                is_expired = CASE
                    WHEN (created_at + interval '7 days') < now() THEN true
                    ELSE false
                END
            """
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invite_token", "is_expired")
    op.drop_column("invite_token", "expires_at")
    # ### end Alembic commands ###
